### PR TITLE
Fix Z.gcd when exactly one argument is zero

### PR DESCRIPTION
**Pull request by vbgl**
The GCD operator is well defined when exactly one of its argument is zero. It should not raise a division-by-zero exception.

### CODE REVIEW

**Comment by antoinemine** [comment]
OK, why not? But your patch only handles the case where both arguments are small integers. The case gcd(0,big_number) would require extra modifications.
Also, is there any sense in stating gcd(0,0)=0, given that gcd(a,a)=a holds for a > 0 ?

**Comment by vbgl** [comment]
On 18/10/2018 10:07, Antoine Miné wrote:

> OK, why not? But your patch only handles the case where both arguments
are small integers. The case gcd(0,big_number) would require extra
modifications.

Unfortunately, a similar modification in the slow path produces
segmentation faults…

As per the documentation
https://gmplib.org/manual/Low_002dlevel-Functions.html#index-mpn_005fgcd, this
is expected. Any hint on how to work around this is welcome.

> Also, is there any sense in stating gcd(0,0)=0, given that gcd(a,a)=a
holds for a > 0 ?

The higher-level function mpz_gcd does this
(https://gmplib.org/manual/Number-Theoretic-Functions.html#index-mpz_005fgcd).

**Comment by antoinemine** [comment]
OK. I added support for gcd(0,large_integer) and gcd(0,0).
Feedbacks are welcome before I merge into master.

**Comment by vbgl** [comment]
Your last change Antoine looks good to me. I’ve run the test-suite of Coq on branch coq/coq#8743 without Emilio’s workaround using this fix: there are a few issues but none seems related to a failing GCD computation. Thanks again.

**Comment by vbgl** [comment]
Thanks for merging. Can we expect a release including this change? Thanks.

**Comment by antoinemine** [comment]
> Thanks for merging. Can we expect a release including this change? Thanks.

Yes, I've made a 1.8 release with this fix.

**Pull request merged**
