### PR TITLE
add @since annotations on infix operators

### PR DESCRIPTION
**Pull request by c-cube**

### CODE REVIEW

**Comment by antoinemine** [comment]
Sorry for the delay. We did not document with @since at all. Yet, there were a lot of additions before (in 1.4) and after (in 1.10), so, to be consistent, I guess we'd have to document them as well (possibly having to do detective work to find the right version). Not sure it is worth it...

**Comment by antoinemine** [comment]
Sure.

**Comment by c-cube** [comment]
added more, going back to 1.1.

**Comment by antoinemine** [comment]
Thanks, this looks good. Merging.

**Pull request merged**
