### PR TITLE
Compatibility with OCaml trunk (4.08.0+dev0)

### PR DESCRIPTION
**Pull request by dhil**
Zarith has been broken with trunk since ocaml/ocaml#1683 as that particular PR introduces changes to the marshalling format and C API. This PR restores compatibility with trunk OCaml.

There may be some work left to make Zarith backwards compatible with `<= 4.07.x` .

### CODE REVIEW

**Comment by antoinemine** [comment]
As feared, with this patch, zarith does not compile with OCaml 4.07. Could you add the proper #ifdef to ensure it keeps compiling?

**Comment by dhil** [comment]
> As feared, with this patch, zarith does not compile with OCaml 4.07. Could you add the proper #ifdef to ensure it keeps compiling?

Sure, I can give it a try. How do you want to manage the disparities in the test suite, in particular the expectation files `zq.output{32,64}`? Do you want to provide two set of files, e.g. one set for before 4.08 and another for 4.08 and upwards? Or only support for 4.08 and upwards?

**Comment by antoinemine** [comment]
OK, thanks!

I suggest we keep the test output as is while 4.07 is the latest version. We'll update the test files when 4.08 is out. It's OK, I think, if "make tests" only works for the latest official OCaml version, no need to make things more complicated. But "make" should work for older and newer versions.

**Comment by dhil** [comment]
@antoinemine I believe the latest commit restores backwards compatibility. I am to compile with 4.02.2, 4.06.1, and 4.08.0+dev0.

> At some point we should test round-trip properties of marshaling followed by unmarshaling, rather than test for exact output of marshaling.

Good point. It should provide robust solution to the disparity-problem. Would you like me to try to incorporate this solution into this PR?

**Comment by antoinemine** [comment]
@dhil I can compile fine with 4.07, thanks!
@xavierleroy very good idea; @dhil, thanks for proposing to implement this in the PR, that'd be nice.

**Comment by dhil** [comment]
@antoinemine apologies for the delay -- I got side-tracked by work :-)

I believe have implemented round tripping for the marshalling test in `chk_bits`. I have updated the test expectations for `zq` accordingly.

**Comment by antoinemine** [comment]
This works well with OCaml 4.07 and 4.08, thanks ! Merged.

**Pull request merged**
